//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timer_lks_2_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class header_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public header_transaction()
        {
            this.detail_transaction = new HashSet<detail_transaction>();
        }
    
        public Nullable<int> id_employee { get; set; }
        public Nullable<int> id_customer { get; set; }
        public int id_header_transaction { get; set; }
        public Nullable<System.DateTime> transaction_date_time__header_transaction { get; set; }
        public Nullable<System.DateTime> complete_estimation_date_time_header_transaction { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_transaction> detail_transaction { get; set; }
        public virtual employee employee { get; set; }
    }
}
